<?php
return array(
    'QINIU_ACCESSKEY' => env('QINIU_ACCESSKEY'),
    'QINIU_SECRETKEY' => env('QINIU_SECRETKEY'),
    'QINIU_BUCKET' => env('QINIU_BUCKET'),

    'OSS_ACCESSKEY' => env('OSS_ACCESSKEY'),
    'OSS_ACCESS_KEY_SECRET'=>env('OSS_ACCESS_KEY_SECRET'),
    'OSS_ENDPOINT'=>env('OSS_ENDPOINT'),
    'OSS_BUCKET'=>env('OSS_BUCKET')
);